import nodemailer from 'nodemailer';
import { getAllSettings } from './settings-service.js';

/**
 * Build nodemailer transport from database settings
 */
async function getTransporter() {
  const settings = await getAllSettings();

  const host = settings.smtp_host || 'smtp.gmail.com';
  const port = parseInt(settings.smtp_port, 10) || 465;
  const isSecure = settings.smtp_secure === '1' || port === 465;
  const user = (settings.smtp_user || '').trim();
  // Strip spaces from Google App Passwords (e.g. "rdfv ukzs nbdo mvir" -> "rdfvukzsnbdomvir")
  const pass = (settings.smtp_pass || '').replace(/\s+/g, '').trim();

  const transporter = nodemailer.createTransport({
    host,
    port,
    secure: isSecure,
    auth: {
      user,
      pass,
    },
    // Useful for Gmail
    tls: {
      rejectUnauthorized: false,
    },
  });

  return { transporter, settings };
}

/**
 * Send notification for a new Contact Us form submission
 */
export async function sendContactNotification({ name, email, subject, message }) {
  try {
    const { transporter, settings } = await getTransporter();
    const receiver = settings.notification_receiver_email || settings.smtp_user || 'rana33994@gmail.com';
    const fromName = settings.smtp_from_name || 'Daily Hukamnama';
    const fromEmail = settings.smtp_from_email || settings.smtp_user;

    const emailSubject = `[Daily Hukamnama] New Contact Message: ${subject || 'General Inquiry'}`;
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background: #ffffff;">
        <div style="background: linear-gradient(135deg, #0f172a, #1e293b); padding: 24px; text-align: center; border-bottom: 3px solid #dd9933;">
          <h2 style="color: #ffffff; margin: 0; font-size: 20px;">Daily Hukamnama – Contact Form</h2>
          <p style="color: #dd9933; margin: 6px 0 0 0; font-size: 13px;">Sachkhand Sri Harmandir Sahib, Amritsar</p>
        </div>
        <div style="padding: 24px; color: #1e293b; font-size: 14px; line-height: 1.6;">
          <p style="margin-top: 0;">You have received a new inquiry via the website contact form:</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; width: 120px; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Name:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(name)}</td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Email:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;"><a href="mailto:${escapeHtml(email)}" style="color: #b87b20;">${escapeHtml(email)}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Subject:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(subject || 'General Inquiry')}</td>
            </tr>
          </table>
          <div style="background: #f8fafc; border-left: 4px solid #dd9933; padding: 14px 18px; border-radius: 4px; margin: 16px 0;">
            <strong style="display: block; margin-bottom: 6px; color: #0f172a;">Message:</strong>
            <div style="white-space: pre-wrap; color: #334155;">${escapeHtml(message)}</div>
          </div>
          <p style="color: #64748b; font-size: 12px; margin-top: 24px;">
            This email was automatically generated by <a href="https://dailyhukamnama.in" style="color: #b87b20;">dailyhukamnama.in</a>.
          </p>
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: `"${fromName}" <${fromEmail}>`,
      to: receiver,
      replyTo: email,
      subject: emailSubject,
      html: htmlContent,
    });

    console.log('Contact notification email sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (err) {
    console.error('Failed to send contact email:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Send notification for a new Volunteer registration
 */
export async function sendVolunteerNotification({ name, email, phone, city, sevaArea, message }) {
  try {
    const { transporter, settings } = await getTransporter();
    const receiver = settings.notification_receiver_email || settings.smtp_user || 'rana33994@gmail.com';
    const fromName = settings.smtp_from_name || 'Daily Hukamnama Seva';
    const fromEmail = settings.smtp_from_email || settings.smtp_user;

    const emailSubject = `[Daily Hukamnama] New Volunteer Application: ${name} (${sevaArea || 'General'})`;
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; background: #ffffff;">
        <div style="background: linear-gradient(135deg, #0f172a, #1e293b); padding: 24px; text-align: center; border-bottom: 3px solid #dd9933;">
          <h2 style="color: #ffffff; margin: 0; font-size: 20px;">Daily Hukamnama – Volunteer Application</h2>
          <p style="color: #dd9933; margin: 6px 0 0 0; font-size: 13px;">Gurmukhi Seva Team Registration</p>
        </div>
        <div style="padding: 24px; color: #1e293b; font-size: 14px; line-height: 1.6;">
          <p style="margin-top: 0;">A devotee has volunteered to contribute seva to Daily Hukamnama:</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; width: 130px; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Volunteer Name:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(name)}</td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Email:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;"><a href="mailto:${escapeHtml(email)}" style="color: #b87b20;">${escapeHtml(email)}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Phone / WhatsApp:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(phone || 'Not provided')}</td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">City / Country:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0;">${escapeHtml(city || 'Not provided')}</td>
            </tr>
            <tr>
              <td style="padding: 8px 12px; font-weight: bold; background: #f8fafc; border-bottom: 1px solid #e2e8f0;">Seva Area:</td>
              <td style="padding: 8px 12px; border-bottom: 1px solid #e2e8f0; color: #b87b20; font-weight: bold;">${escapeHtml(sevaArea || 'General')}</td>
            </tr>
          </table>
          ${message ? `
            <div style="background: #f8fafc; border-left: 4px solid #dd9933; padding: 14px 18px; border-radius: 4px; margin: 16px 0;">
              <strong style="display: block; margin-bottom: 6px; color: #0f172a;">Skills & Experience:</strong>
              <div style="white-space: pre-wrap; color: #334155;">${escapeHtml(message)}</div>
            </div>
          ` : ''}
          <p style="color: #64748b; font-size: 12px; margin-top: 24px;">
            Submitted via the Volunteers page on <a href="https://dailyhukamnama.in/volunteers" style="color: #b87b20;">dailyhukamnama.in</a>.
          </p>
        </div>
      </div>
    `;

    const info = await transporter.sendMail({
      from: `"${fromName}" <${fromEmail}>`,
      to: receiver,
      replyTo: email,
      subject: emailSubject,
      html: htmlContent,
    });

    console.log('Volunteer notification email sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (err) {
    console.error('Failed to send volunteer email:', err);
    return { success: false, error: err.message };
  }
}

/**
 * Send a quick test email to verify SMTP configuration
 */
export async function sendTestEmail(targetEmail) {
  try {
    const { transporter, settings } = await getTransporter();
    const recipient = targetEmail || settings.notification_receiver_email || settings.smtp_user || 'rana33994@gmail.com';
    const fromName = settings.smtp_from_name || 'Daily Hukamnama';
    const fromEmail = settings.smtp_from_email || settings.smtp_user;

    const info = await transporter.sendMail({
      from: `"${fromName}" <${fromEmail}>`,
      to: recipient,
      subject: `[Daily Hukamnama] Google SMTP Test Email – Success!`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 550px; margin: 20px auto; border: 1px solid #cbd5e1; border-radius: 12px; overflow: hidden;">
          <div style="background: #0f172a; padding: 20px; text-align: center; border-bottom: 3px solid #dd9933;">
            <h2 style="color: #ffffff; margin: 0;">SMTP Test Successful!</h2>
            <p style="color: #dd9933; margin: 4px 0 0 0; font-size: 12px;">Daily Hukamnama System</p>
          </div>
          <div style="padding: 20px; color: #1e293b; font-size: 14px;">
            <p>Congratulations! Your Google SMTP configuration is working perfectly.</p>
            <ul style="color: #475569; font-size: 13px;">
              <li><strong>SMTP Host:</strong> ${settings.smtp_host}</li>
              <li><strong>SMTP Port:</strong> ${settings.smtp_port}</li>
              <li><strong>User:</strong> ${settings.smtp_user}</li>
              <li><strong>Timestamp:</strong> ${new Date().toISOString()}</li>
            </ul>
            <p style="color: #10b981; font-weight: bold;">Contact and Volunteer form submissions will now be delivered to this email.</p>
          </div>
        </div>
      `,
    });

    return { success: true, messageId: info.messageId, recipient };
  } catch (err) {
    console.error('Test email failed:', err);
    return { success: false, error: err.message };
  }
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
